config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :memes
  root "memes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/meme.rb
# == Schema Information
#
# Table name: memes
#
#  id         :integer          not null, primary key
#  title      :string
#  image_url  :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Meme < ApplicationRecord
    validates :title, presence: { message: "must be provided" }, length: { minimum: 5, maximum: 100, message: "should be between 5 and 100 characters" }
    validates :image_url, presence: { message: "must be provided" }
    validates :author_id, presence: true

    has_one_attached :image_url

    belongs_to :user, foreign_key: 'author_id', optional: true
    enum status: { pending: 0, approved: 1, banned: 2 }
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  age                    :integer
#  username               :string
#  avatar                 :string
#
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :age, numericality: { only_integer: true, greater_than: 0 }, allow_nil: true
  validates :username, presence: true, uniqueness: true
  validates :avatar, presence: true
  has_one_attached :avatar
  has_many :authored_memes, class_name: 'Meme', foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:age, :username, :avatar])
      devise_parameter_sanitizer.permit(:account_update, keys: [:age, :username, :avatar])
    end
  
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
  before_action :set_meme, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  
  def index
    @memes = Meme.all
    
  end

  def show
  end

  def new
    @meme = Meme.new
  end

  def edit
  end

  def create
    @meme = Meme.new(meme_params)

    respond_to do |format|
      if @meme.save
        format.html { redirect_to meme_url(@meme), notice: "Meme was successfully created." }
        format.json { render :show, status: :created, location: @meme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @meme.update(meme_params)
        format.html { redirect_to meme_url(@meme), notice: "Meme was successfully updated." }
        format.json { render :show, status: :ok, location: @meme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meme.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meme.destroy

    respond_to do |format|
      format.html { redirect_to memes_url, notice: "Meme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_meme
      @meme = Meme.find(params[:id])
    end

    def meme_params
      params.require(:meme).permit(:title, :image_url, :author_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fourmemes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'switch' %>
    <%= javascript_include_tag 'alerts' %>


  </head>

  <body>
    <%= render 'navigation/navbar' %>
    <div class="container mt-3">
      <div class="row">
        <div class="col-md-3 left-sidebar">
          <%= render 'navigation/sidebar' %>
        </div>
        <div class="col-md-6 center-column">
          <%= render 'shared/alerts' %>
          <%= yield %>
        </div>
        <div class="col-md-3 right-column">
          <%= yield :right_column %>
            <%= render 'navigation/right_column' %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_with(model: meme, multipart: true) do |form| %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
    
    <%= form.hidden_field  :author_id, value: current_user.id %>
    <%= form.hidden_field :added_by, value: current_user.username %>
    <% if meme.errors.has_key?(:title) %>
      <div style="color: red">
        <%= meme.errors.full_messages_for(:title).join(", ") %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.label :image_url, style: "display: block" %>
    <%= form.file_field :image_url %>
    <% if meme.errors.has_key?(:image_url) %>
      <div style="color: red">
        <%= meme.errors.full_messages_for(:image_url).join(", ") %>
      </div>
    <% end %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/memes/_meme.html.erb
<div id="<%= dom_id(meme) %>" class="card text-center mb-4" style="background-color: #e6f7ff; border: 1px solid #b3d9ff;">
  <%= link_to meme_path(meme), class: "card-header text-decoration-none" do %>
    <h5 class="font-weight-bold m-0 text-dark">
      <%= meme.title %>
    </h5>
  <% end %>

  <div class="card-body d-flex justify-content-center align-items-center">
    <%= image_tag(rails_blob_url(meme.image_url), size: 400, class: "img-fluid rounded") %>
  </div>

  <div class="card-footer text-left mt-auto">
    <div class="d-flex align-items-center mb-2">
      <% user = User.find_by(id: meme.author_id) %>

      <% if user.present? %>
        <%= image_tag(user.avatar, class: "rounded-circle mr-2", width: "32", height: "32", alt: "author_profile_avatar") %>
      <% else %>
        <!-- Obsługa przypadku, gdy użytkownik nie istnieje -->
      <% end %>
      <span class="ms-2"><%= User.find_by(id: meme.author_id)&.username %></span>
      <%# <button type="button" class="btn btn-primary btn-sm ml-auto h5">
        4like it!
      </button> %>
    </div>

    <div class="row">
      <div class="col-md-12 text-muted">
        <%= time_ago_in_words(meme.created_at) %> ago
      </div>
    </div>
  </div>
</div>

app/views/memes/edit.html.erb
<h1>Editing meme</h1>

<%= render "form", meme: @meme %>

<br>

<div>
  <%= link_to "Show this meme", @meme %> |
  <%= link_to "Back to memes", memes_path %>
</div>

app/views/memes/index.html.erb
<div id="memes">
  <% @memes.each do |meme| %>
    <%= render meme %>

  <% end %>
</div>

app/views/memes/new.html.erb
<h1>New meme</h1>

<%= render "form", meme: @meme %>

<br>

<div>
  <%= link_to "Back to memes", memes_path %>
</div>

app/views/memes/show.html.erb
<%= render @meme %>

<div>
  <%= link_to "Edit this meme", edit_meme_path(@meme) %> |
  <%= link_to "Back to memes", memes_path %>

  <%= button_to "Destroy this meme", @meme, method: :delete %>
</div>

app/views/navigation/_navbar.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg border-bottom">
  <div class="container">
    <a class="navbar-brand" href="#">4memes</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
              <li class="nav-item">
          <a id="toggleButton" class="nav-link" aria-current="page" href="#" title="hide menu">
            <i class="bi bi-list fs-3 me-2"></i> 
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= root_path %>" title="home">
            <i class="bi bi-house-door fs-3 me-2"></i> 
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#" title="top rated">
            <i class="bi bi-bar-chart-line-fill fs-3 me-2"></i> 
          </a>
        <li>
        <li class="nav-item">
          <a class="nav-link disabled" aria-current="page" href="#">
            <i class="bi bi-house-door fs-3 me-2"></i> 
          </a>
        </li>
      </ul>
    </div>

    <div class="navbar-nav ms-auto">
      <% if current_user %>
        <!-- Zalogowany -->
        <li class="nav-item">
          <%= link_to edit_user_registration_path, class: "nav-link" do %>
            <i class="bi bi-grid-fill fs-3 me-2"></i>
          <% end %>
        </li>
        <li class="nav-item">
          <%= button_to destroy_user_session_path, method: :delete, class: "nav-link" do %>
            <i class="bi bi-power fs-3 me-2"></i>
          <% end %>
        </li>
      <% else %>
        <!-- Niezalogowany -->
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </div>
  </div>
</nav>

app/views/navigation/_right_column.erb
<div class= "d-flex justify-content-center align-items-center flex-column">
<% if current_user %>
<h1><%= current_user.username %>! </h1>
<%= image_tag(current_user.avatar, size: '150x150', class:"rounded-circle avatar-pp1 p-1 d-inline-block mb-2", alt:"user_profile_picture") if current_user.avatar.attached? %>
</div>
<p> Memes uploaded: </p>
<p> Meme coins: </p>
<% else %>
<h1> Hello Memes! </h1>
<p> Sign in to be a part of 4memes </p>
<% end %>

app/views/navigation/_sidebar.html.erb
<h2> Categories </h2>
<ul class="nav flex-column">
  <li class="nav-item">
    <a class="nav-link active" aria-current="page" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" aria-disabled="true">Disabled</a>
  </li>
</ul>

app/views/shared/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key.to_s == 'notice' ? 'success' : 'danger' %> alert-dismissible fade show flash-message" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>